import Course from "./Course.js";

// Dictionary for extractDaysOfWeek
let dict = {
  "M" : "Monday",
  "T" : "Tuesday",
  "W" : "Wednesday",
  "R" : "Thursday",
  "F" : "Friday",
  "S" : "Saturday",
  "MWF": "Monday Wednesday Friday",
  "MW": "Monday Wednesday",
  "TR": "Tuesday Thursday",
};

// Data from web scraping
// let result = [
//     {
//       select: 'NR',
//       crn: '20006',
//       subj: 'RHET',
//       crse: '103',
//       sec: '01',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'TR',
//       time: '08:00 am-09:45 am',
//       cap: '22',
//       act: '14',
//       rem: '8',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Brian S  Vannice (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'NR',
//       crn: '20007',
//       subj: 'RHET',
//       crse: '103',
//       sec: '02',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'MWF',
//       time: '10:30 am-11:35 am',
//       cap: '22',
//       act: '21',
//       rem: '1',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Ben David  Linzer (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'NR',
//       crn: '20008',
//       subj: 'RHET',
//       crse: '103',
//       sec: '03',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'MWF',
//       time: '08:00 am-09:05 am',
//       cap: '22',
//       act: '21',
//       rem: '1',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Kathleen Anne  Arnolfo (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'C',
//       crn: '20009',
//       subj: 'RHET',
//       crse: '103',
//       sec: '04',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'TR',
//       time: '09:55 am-11:40 am',
//       cap: '22',
//       act: '22',
//       rem: '0',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Devon C  Holmes (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'C',
//       crn: '20010',
//       subj: 'RHET',
//       crse: '103',
//       sec: '05',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'MWF',
//       time: '10:30 am-11:35 am',
//       cap: '22',
//       act: '22',
//       rem: '0',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Leigh Taylor  Meredith (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'C',
//       crn: '20011',
//       subj: 'RHET',
//       crse: '103',
//       sec: '06',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'MWF',
//       time: '02:15 pm-03:20 pm',
//       cap: '22',
//       act: '22',
//       rem: '0',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Leigh Taylor  Meredith (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'NR',
//       crn: '20012',
//       subj: 'RHET',
//       crse: '103',
//       sec: '07',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'TR',
//       time: '04:35 pm-06:20 pm',
//       cap: '22',
//       act: '16',
//       rem: '6',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Angela Ehle  Beasley (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'NR',
//       crn: '20013',
//       subj: 'RHET',
//       crse: '103',
//       sec: '09',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'TR',
//       time: '02:40 pm-04:25 pm',
//       cap: '22',
//       act: '18',
//       rem: '4',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Brian S  Vannice (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'C',
//       crn: '20014',
//       subj: 'RHET',
//       crse: '103',
//       sec: '10',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'MWF',
//       time: '11:45 am-12:50 pm',
//       cap: '22',
//       act: '22',
//       rem: '0',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'John B  Ryan (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'C',
//       crn: '20017',
//       subj: 'RHET',
//       crse: '103',
//       sec: '13',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'MWF',
//       time: '09:15 am-10:20 am',
//       cap: '22',
//       act: '22',
//       rem: '0',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Marc   Martin (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'NR',
//       crn: '20018',
//       subj: 'RHET',
//       crse: '103',
//       sec: '14',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'MW',
//       time: '06:30 pm-08:15 pm',
//       cap: '22',
//       act: '21',
//       rem: '1',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Michael A  Rozendal (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'NR',
//       crn: '20019',
//       subj: 'RHET',
//       crse: '103',
//       sec: '15',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'MWF',
//       time: '01:00 pm-02:05 pm',
//       cap: '22',
//       act: '15',
//       rem: '7',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Kathleen Anne  Arnolfo (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'C',
//       crn: '20020',
//       subj: 'RHET',
//       crse: '103',
//       sec: '16',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'TR',
//       time: '06:30 pm-08:15 pm',
//       cap: '22',
//       act: '22',
//       rem: '0',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Erik W  Christianson (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'C',
//       crn: '20021',
//       subj: 'RHET',
//       crse: '103',
//       sec: '17',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'MW',
//       time: '04:45 pm-06:25 pm',
//       cap: '22',
//       act: '22',
//       rem: '0',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Joanne W  Babin (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'NR',
//       crn: '20023',
//       subj: 'RHET',
//       crse: '103',
//       sec: '19',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'MWF',
//       time: '11:45 am-12:50 pm',
//       cap: '22',
//       act: '20',
//       rem: '2',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Erik W  Christianson (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'C',
//       crn: '20025',
//       subj: 'RHET',
//       crse: '103',
//       sec: '21',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'TR',
//       time: '12:45 pm-02:30 pm',
//       cap: '22',
//       act: '22',
//       rem: '0',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Devon C  Holmes (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'C',
//       crn: '20027',
//       subj: 'RHET',
//       crse: '103',
//       sec: '23',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'TR',
//       time: '12:45 pm-02:30 pm',
//       cap: '22',
//       act: '22',
//       rem: '0',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Nicole Gonzales  Howell (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'NR',
//       crn: '20029',
//       subj: 'RHET',
//       crse: '103',
//       sec: '25',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'TR',
//       time: '08:00 am-09:45 am',
//       cap: '22',
//       act: '18',
//       rem: '4',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'David C  Ryan (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'C',
//       crn: '21985',
//       subj: 'RHET',
//       crse: '103',
//       sec: '26',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Speaking',
//       days: 'TR',
//       time: '09:55 am-11:40 am',
//       cap: '22',
//       act: '22',
//       rem: '0',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Michelle R  LaVigne (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'NR',
//       crn: '20030',
//       subj: 'RHET',
//       crse: '104',
//       sec: '01',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Argumentation and Debate',
//       days: 'MWF',
//       time: '01:00 pm-02:05 pm',
//       cap: '12',
//       act: '9',
//       rem: '3',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Robert   Boller (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'NR',
//       crn: '20044',
//       subj: 'RHET',
//       crse: '111',
//       sec: '01',
//       cmp: 'ODP',
//       cred: '4.000',
//       title: 'Public Spkng/Health Profession',
//       days: 'MWF',
//       time: '09:15 am-10:20 am',
//       cap: '22',
//       act: '21',
//       rem: '1',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Bryan Burton  Whaley (P)',
//       date: '01/25-05/13',
//       location: 'RMT ',
//       attribute: 'Core A1 Public Speaking'
//     },
//     {
//       select: 'NR',
//       crn: '21009', // this 
//       subj: 'SII', // this 
//       crse: '325', // this 
//       sec: '01', // this 
//       cmp: 'ODP', 
//       cred: '2.000', // this 
//       title: 'SYM: Public Speaking', // this 
//       days: 'M', // We can assume this for now on 1 day.
//       time: '01:00 pm-02:35 pm', //IMPORTANT
//       cap: '14', 
//       act: '10',
//       rem: '4',
//       wlCap: '0',
//       wlAct: '0',
//       wlRem: '0',
//       xlCap: '0',
//       xlAct: '0',
//       xlRem: '0',
//       instructor: 'Michelle R  LaVigne (P)', // this
//       date: '01/25-05/13', // this
//       location: 'RMT ', 
//       attribute: 'Core A1 Public Speaking' // This 
//     }
// ];

let result =
  [
    {
      select: 'NR',
      crn: '20006',
      subj: 'RHET',
      crse: '103',
      sec: '01',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'TR',
      time: '08:00 am-09:45 am',
      cap: '22',
      act: '14',
      rem: '8',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Brian S  Vannice (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'NR',
      crn: '20007',
      subj: 'RHET',
      crse: '103',
      sec: '02',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'MWF',
      time: '10:30 am-11:35 am',
      cap: '22',
      act: '21',
      rem: '1',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Ben David  Linzer (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'NR',
      crn: '20008',
      subj: 'RHET',
      crse: '103',
      sec: '03',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'MWF',
      time: '08:00 am-09:05 am',
      cap: '22',
      act: '21',
      rem: '1',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Kathleen Anne  Arnolfo (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'C',
      crn: '20009',
      subj: 'RHET',
      crse: '103',
      sec: '04',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'TR',
      time: '09:55 am-11:40 am',
      cap: '22',
      act: '22',
      rem: '0',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Devon C  Holmes (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'C',
      crn: '20010',
      subj: 'RHET',
      crse: '103',
      sec: '05',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'MWF',
      time: '10:30 am-11:35 am',
      cap: '22',
      act: '22',
      rem: '0',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Leigh Taylor  Meredith (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'C',
      crn: '20011',
      subj: 'RHET',
      crse: '103',
      sec: '06',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'MWF',
      time: '02:15 pm-03:20 pm',
      cap: '22',
      act: '22',
      rem: '0',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Leigh Taylor  Meredith (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'NR',
      crn: '20012',
      subj: 'RHET',
      crse: '103',
      sec: '07',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'TR',
      time: '04:35 pm-06:20 pm',
      cap: '22',
      act: '16',
      rem: '6',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Angela Ehle  Beasley (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'NR',
      crn: '20013',
      subj: 'RHET',
      crse: '103',
      sec: '09',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'TR',
      time: '02:40 pm-04:25 pm',
      cap: '22',
      act: '18',
      rem: '4',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Brian S  Vannice (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'C',
      crn: '20014',
      subj: 'RHET',
      crse: '103',
      sec: '10',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'MWF',
      time: '11:45 am-12:50 pm',
      cap: '22',
      act: '22',
      rem: '0',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'John B  Ryan (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'C',
      crn: '20017',
      subj: 'RHET',
      crse: '103',
      sec: '13',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'MWF',
      time: '09:15 am-10:20 am',
      cap: '22',
      act: '22',
      rem: '0',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Marc   Martin (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'NR',
      crn: '20018',
      subj: 'RHET',
      crse: '103',
      sec: '14',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'MW',
      time: '06:30 pm-08:15 pm',
      cap: '22',
      act: '21',
      rem: '1',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Michael A  Rozendal (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'NR',
      crn: '20019',
      subj: 'RHET',
      crse: '103',
      sec: '15',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'MWF',
      time: '01:00 pm-02:05 pm',
      cap: '22',
      act: '15',
      rem: '7',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Kathleen Anne  Arnolfo (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'C',
      crn: '20020',
      subj: 'RHET',
      crse: '103',
      sec: '16',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'TR',
      time: '06:30 pm-08:15 pm',
      cap: '22',
      act: '22',
      rem: '0',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Erik W  Christianson (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'C',
      crn: '20021',
      subj: 'RHET',
      crse: '103',
      sec: '17',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'MW',
      time: '04:45 pm-06:25 pm',
      cap: '22',
      act: '22',
      rem: '0',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Joanne W  Babin (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'NR',
      crn: '20023',
      subj: 'RHET',
      crse: '103',
      sec: '19',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'MWF',
      time: '11:45 am-12:50 pm',
      cap: '22',
      act: '20',
      rem: '2',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Erik W  Christianson (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'C',
      crn: '20025',
      subj: 'RHET',
      crse: '103',
      sec: '21',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'TR',
      time: '12:45 pm-02:30 pm',
      cap: '22',
      act: '22',
      rem: '0',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Devon C  Holmes (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'C',
      crn: '20027',
      subj: 'RHET',
      crse: '103',
      sec: '23',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'TR',
      time: '12:45 pm-02:30 pm',
      cap: '22',
      act: '22',
      rem: '0',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Nicole Gonzales  Howell (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'NR',
      crn: '20029',
      subj: 'RHET',
      crse: '103',
      sec: '25',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'TR',
      time: '08:00 am-09:45 am',
      cap: '22',
      act: '18',
      rem: '4',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'David C  Ryan (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'C',
      crn: '21985',
      subj: 'RHET',
      crse: '103',
      sec: '26',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Speaking',
      days: 'TR',
      time: '09:55 am-11:40 am',
      cap: '22',
      act: '22',
      rem: '0',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Michelle R  LaVigne (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'NR',
      crn: '20030',
      subj: 'RHET',
      crse: '104',
      sec: '01',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Argumentation and Debate',
      days: 'MWF',
      time: '01:00 pm-02:05 pm',
      cap: '12',
      act: '9',
      rem: '3',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Robert   Boller (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'NR',
      crn: '20044',
      subj: 'RHET',
      crse: '111',
      sec: '01',
      cmp: 'ODP',
      cred: '4.000',
      title: 'Public Spkng/Health Profession',
      days: 'MWF',
      time: '09:15 am-10:20 am',
      cap: '22',
      act: '21',
      rem: '1',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Bryan Burton  Whaley (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: 'NR',
      crn: '21009',
      subj: 'SII',
      crse: '325',
      sec: '01',
      cmp: 'ODP',
      cred: '2.000',
      title: 'SYM: Public Speaking',
      days: 'M',
      time: '01:00 pm-02:35 pm',
      cap: '14',
      act: '10',
      rem: '4',
      wlCap: '0',
      wlAct: '0',
      wlRem: '0',
      xlCap: '0',
      xlAct: '0',
      xlRem: '0',
      instructor: 'Michelle R  LaVigne (P)',
      date: '01/25-05/13',
      location: 'RMT ',
      attribute: 'Core A1 Public Speaking'
    },
    {
      select: "NR",
      crn: "20623",
      subj: "HONC",
      crse: "131",
      sec: "01",
      cmp: "ODP",
      cred: "2.000",
      title: "Rhetoric Across Borders II",
      days: "T",
      time: "09:55 am-11:40 am",
      cap: "24",
      act: "23",
      rem: "1",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Michael A  Rozendal (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20624",
      subj: "HONC",
      crse: "131",
      sec: "02",
      cmp: "ODP",
      cred: "2.000",
      title: "Rhetoric Across Borders II",
      days: "R",
      time: "09:55 am-11:40 am",
      cap: "24",
      act: "15",
      rem: "9",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Michael A  Rozendal (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20625",
      subj: "HONC",
      crse: "131",
      sec: "03",
      cmp: "ODP",
      cred: "2.000",
      title: "Rhetoric Across Borders II",
      days: "W",
      time: "04:45 pm-06:25 pm",
      cap: "24",
      act: "22",
      rem: "2",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Leigh Taylor  Meredith (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20626",
      subj: "HONC",
      crse: "131",
      sec: "04",
      cmp: "ODP",
      cred: "2.000",
      title: "Rhetoric Across Borders II",
      days: "M",
      time: "04:45 pm-06:25 pm",
      cap: "24",
      act: "21",
      rem: "3",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Michael A  Rozendal (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20045",
      subj: "RHET",
      crse: "120",
      sec: "01",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "MWF",
      time: "09:15 am-10:20 am",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Mark D  Meritt (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20046",
      subj: "RHET",
      crse: "120",
      sec: "02",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "MWF",
      time: "08:00 am-09:05 am",
      cap: "22",
      act: "21",
      rem: "1",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Patricia   Kalman (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20047",
      subj: "RHET",
      crse: "120",
      sec: "03",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "MWF",
      time: "02:15 pm-03:20 pm",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Christopher Paul  DeLorenzo (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20048",
      subj: "RHET",
      crse: "120",
      sec: "04",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "MWF",
      time: "10:30 am-11:35 am",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Mark D  Meritt (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20049",
      subj: "RHET",
      crse: "120",
      sec: "05",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "MWF",
      time: "09:15 am-10:20 am",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Patricia   Kalman (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20050",
      subj: "RHET",
      crse: "120",
      sec: "06",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "MWF",
      time: "01:00 pm-02:05 pm",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Mark D  Meritt (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20051",
      subj: "RHET",
      crse: "120",
      sec: "07",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "MWF",
      time: "03:30 pm-04:35 pm",
      cap: "22",
      act: "20",
      rem: "2",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Cynthia M  Schultes (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20052",
      subj: "RHET",
      crse: "120",
      sec: "08",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "MW",
      time: "04:45 pm-06:25 pm",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Kara J  Knafelc (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20053",
      subj: "RHET",
      crse: "120",
      sec: "10",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "TR",
      time: "08:00 am-09:45 am",
      cap: "22",
      act: "21",
      rem: "1",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Robert Keller  Bathrick (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20054",
      subj: "RHET",
      crse: "120",
      sec: "11",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "MWF",
      time: "01:00 pm-02:05 pm",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Cynthia M  Schultes (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20055",
      subj: "RHET",
      crse: "120",
      sec: "12",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "TR",
      time: "04:35 pm-06:20 pm",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Brandon Vaden  Janiak (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20057",
      subj: "RHET",
      crse: "120",
      sec: "14",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "MWF",
      time: "11:45 am-12:50 pm",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Ronald   Key (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20059",
      subj: "RHET",
      crse: "120",
      sec: "15",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "MWF",
      time: "10:30 am-11:35 am",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Marlene I  Mahony (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20060",
      subj: "RHET",
      crse: "120",
      sec: "16",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "TR",
      time: "12:45 pm-02:30 pm",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Leslie   Dennen (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20062",
      subj: "RHET",
      crse: "120",
      sec: "18",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "TR",
      time: "06:30 pm-08:15 pm",
      cap: "22",
      act: "18",
      rem: "4",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Ellen K  Thompson (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20063",
      subj: "RHET",
      crse: "120",
      sec: "19",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "MWF",
      time: "02:15 pm-03:20 pm",
      cap: "22",
      act: "18",
      rem: "4",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Ronald   Key (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20067",
      subj: "RHET",
      crse: "120",
      sec: "23",
      cmp: "ODP",
      cred: "4.000",
      title: "Written Communication II",
      days: "MWF",
      time: "01:00 pm-02:05 pm",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Christopher Paul  DeLorenzo (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20070",
      subj: "RHET",
      crse: "126",
      sec: "01",
      cmp: "ODP",
      cred: "4.000",
      title: "MBS: Wrtg/Spkg in Cmty",
      days: "MWF",
      time: "11:45 am-02:05 pm",
      cap: "20",
      act: "15",
      rem: "5",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "David M  Holler (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20072",
      subj: "RHET",
      crse: "131",
      sec: "01",
      cmp: "ODP",
      cred: "4.000",
      title: "Written and Oral Communication",
      days: "TR",
      time: "09:55 am-11:40 am",
      cap: "21",
      act: "21",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Gina Marie Ottoboni  Stahl-Haven (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20073",
      subj: "RHET",
      crse: "131",
      sec: "02",
      cmp: "ODP",
      cred: "4.000",
      title: "Written and Oral Communication",
      days: "TR",
      time: "12:45 pm-02:30 pm",
      cap: "22",
      act: "20",
      rem: "2",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "James Warren   Boyd (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20074",
      subj: "RHET",
      crse: "131",
      sec: "03",
      cmp: "ODP",
      cred: "4.000",
      title: "Written and Oral Communication",
      days: "MWF",
      time: "11:45 am-12:50 pm",
      cap: "22",
      act: "19",
      rem: "3",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Robert   Boller (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20075",
      subj: "RHET",
      crse: "131",
      sec: "04",
      cmp: "ODP",
      cred: "4.000",
      title: "Written and Oral Communication",
      days: "TR",
      time: "02:40 pm-04:25 pm",
      cap: "22",
      act: "20",
      rem: "2",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Devon C  Holmes (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20076",
      subj: "RHET",
      crse: "131",
      sec: "05",
      cmp: "ODP",
      cred: "4.000",
      title: "Written and Oral Communication",
      days: "MWF",
      time: "02:15 pm-03:20 pm",
      cap: "22",
      act: "19",
      rem: "3",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Patrick K  McDonnell (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20077",
      subj: "RHET",
      crse: "131",
      sec: "06",
      cmp: "ODP",
      cred: "4.000",
      title: "Written and Oral Communication",
      days: "TR",
      time: "02:40 pm-04:25 pm",
      cap: "22",
      act: "14",
      rem: "8",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "James Warren   Boyd (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20078",
      subj: "RHET",
      crse: "131",
      sec: "07",
      cmp: "ODP",
      cred: "4.000",
      title: "Written and Oral Communication",
      days: "TR",
      time: "02:40 pm-04:25 pm",
      cap: "22",
      act: "13",
      rem: "9",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Leslie   Dennen (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20079",
      subj: "RHET",
      crse: "131",
      sec: "08",
      cmp: "ODP",
      cred: "4.000",
      title: "Written and Oral Communication",
      days: "TR",
      time: "08:00 am-09:45 am",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Gina Marie Ottoboni  Stahl-Haven (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20080",
      subj: "RHET",
      crse: "131",
      sec: "09",
      cmp: "ODP",
      cred: "4.000",
      title: "Written and Oral Communication",
      days: "MWF",
      time: "01:00 pm-02:05 pm",
      cap: "22",
      act: "18",
      rem: "4",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Patrick K  McDonnell (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20081",
      subj: "RHET",
      crse: "131",
      sec: "10",
      cmp: "ODP",
      cred: "4.000",
      title: "Written and Oral Communication",
      days: "MWF",
      time: "09:15 am-10:20 am",
      cap: "22",
      act: "15",
      rem: "7",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Michael James  Hammond (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20082",
      subj: "RHET",
      crse: "131",
      sec: "11",
      cmp: "ODP",
      cred: "4.000",
      title: "Written and Oral Communication",
      days: "MW",
      time: "06:30 pm-08:15 pm",
      cap: "22",
      act: "17",
      rem: "5",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Maximilian H  DeLaure (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20083",
      subj: "RHET",
      crse: "131",
      sec: "12",
      cmp: "ODP",
      cred: "4.000",
      title: "Written and Oral Communication",
      days: "MW",
      time: "04:45 pm-06:25 pm",
      cap: "22",
      act: "14",
      rem: "8",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Maximilian H  DeLaure (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20087",
      subj: "RHET",
      crse: "195",
      sec: "01",
      cmp: "ODP",
      cred: "4.000",
      title: "FYS: Language & Power",
      days: "MWF",
      time: "11:45 am-12:50 pm",
      cap: "18",
      act: "15",
      rem: "3",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Genevieve   Leung (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "21990",
      subj: "RHET",
      crse: "195",
      sec: "02",
      cmp: "ODP",
      cred: "4.000",
      title: "FYS:Rhetoric & Free Expression",
      days: "TR",
      time: "12:45 pm-02:30 pm",
      cap: "18",
      act: "18",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Theodore   Matula (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20088",
      subj: "RHET",
      crse: "195",
      sec: "03",
      cmp: "ODP",
      cred: "4.000",
      title: "FYS: Sidewalks & Public Space",
      days: "MWF",
      time: "01:00 pm-02:05 pm",
      cap: "18",
      act: "15",
      rem: "3",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Nicole M  Mauro (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20089",
      subj: "RHET",
      crse: "203",
      sec: "01",
      cmp: "ODP",
      cred: "4.000",
      title: "Writing in Psychology",
      days: "MW",
      time: "04:45 pm-06:25 pm",
      cap: "22",
      act: "16",
      rem: "6",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Doreen   Ewert (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20090",
      subj: "RHET",
      crse: "203",
      sec: "02",
      cmp: "ODP",
      cred: "4.000",
      title: "Writing in Psychology",
      days: "TR",
      time: "09:55 am-11:40 am",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Lisa E  Biesemeyer (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20091",
      subj: "RHET",
      crse: "203",
      sec: "03",
      cmp: "ODP",
      cred: "4.000",
      title: "Writing in Psychology",
      days: "TR",
      time: "02:40 pm-04:25 pm",
      cap: "22",
      act: "15",
      rem: "7",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Susana   Leong (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20092",
      subj: "RHET",
      crse: "203",
      sec: "04",
      cmp: "ODP",
      cred: "4.000",
      title: "Writing in Psychology",
      days: "TR",
      time: "08:00 am-09:45 am",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Lisa E  Biesemeyer (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20093",
      subj: "RHET",
      crse: "203",
      sec: "05",
      cmp: "ODP",
      cred: "4.000",
      title: "Writing in Psychology",
      days: "TR",
      time: "12:45 pm-02:30 pm",
      cap: "22",
      act: "16",
      rem: "6",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Doreen   Ewert (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20094",
      subj: "RHET",
      crse: "206",
      sec: "01",
      cmp: "ODP",
      cred: "4.000",
      title: "Writing for the Sciences",
      days: "TR",
      time: "08:00 am-09:45 am",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Brandon R  Brown (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20095",
      subj: "RHET",
      crse: "250",
      sec: "01",
      cmp: "ODP",
      cred: "4.000",
      title: "Academic Writing at USF",
      days: "TR",
      time: "12:45 pm-02:30 pm",
      cap: "22",
      act: "20",
      rem: "2",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Veronica Xavier  Andrew (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20097",
      subj: "RHET",
      crse: "250",
      sec: "03",
      cmp: "ODP",
      cred: "4.000",
      title: "Academic Writing at USF",
      days: "MWF",
      time: "03:30 pm-04:35 pm",
      cap: "22",
      act: "20",
      rem: "2",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Regina A  Arnold (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "22802",
      subj: "RHET",
      crse: "250",
      sec: "04",
      cmp: "ODP",
      cred: "4.000",
      title: "Academic Writing at USF",
      days: "MW",
      time: "04:45 pm-06:25 pm",
      cap: "22",
      act: "17",
      rem: "5",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Regina A  Arnold (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20099",
      subj: "RHET",
      crse: "250",
      sec: "22",
      cmp: "ODP",
      cred: "4.000",
      title: "Academic Writing at USF",
      days: "M",
      time: "05:00 pm-08:30 pm",
      cap: "22",
      act: "19",
      rem: "3",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Kendon Carl  Kurzer (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20100",
      subj: "RHET",
      crse: "295",
      sec: "01",
      cmp: "ODP",
      cred: "4.000",
      title: "TYS: NewMedia/YouMedia",
      days: "MWF",
      time: "02:15 pm-03:20 pm",
      cap: "18",
      act: "17",
      rem: "1",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Cathy   Gabor (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "20101",
      subj: "RHET",
      crse: "295",
      sec: "02",
      cmp: "ODP",
      cred: "4.000",
      title: "TYS: Rhetoric of Human Rights",
      days: "TR",
      time: "02:40 pm-04:25 pm",
      cap: "18",
      act: "15",
      rem: "3",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Julie A  Sullivan (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20103",
      subj: "RHET",
      crse: "310",
      sec: "01",
      cmp: "ODP",
      cred: "4.000",
      title: "Business & Technical Writing",
      days: "MW",
      time: "04:45 pm-06:25 pm",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Evan L  Elliot (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp",
      "undefined": ""
  },
  {
      select: "C",
      crn: "20105",
      subj: "RHET",
      crse: "310",
      sec: "03",
      cmp: "ODP",
      cred: "4.000",
      title: "Business & Technical Writing",
      days: "TR",
      time: "06:30 pm-08:15 pm",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Roberta A  D'Alois (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "C",
      crn: "20106",
      subj: "RHET",
      crse: "310",
      sec: "04",
      cmp: "ODP",
      cred: "4.000",
      title: "Business & Technical Writing",
      days: "TR",
      time: "12:45 pm-02:30 pm",
      cap: "22",
      act: "22",
      rem: "0",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Ben David  Linzer (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "21995",
      subj: "RHET",
      crse: "315",
      sec: "01",
      cmp: "ODP",
      cred: "4.000",
      title: "Rhetoric of Caring",
      days: "TR",
      time: "04:35 pm-06:20 pm",
      cap: "20",
      act: "17",
      rem: "3",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Ellen K  Thompson (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "21994",
      subj: "RHET",
      crse: "320",
      sec: "01",
      cmp: "ODP",
      cred: "4.000",
      title: "How Language Works",
      days: "TR",
      time: "09:55 am-11:40 am",
      cap: "22",
      act: "11",
      rem: "11",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Doreen   Ewert (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "21603",
      subj: "SOC",
      crse: "297",
      sec: "01",
      cmp: "ODP",
      cred: "4.000",
      title: "Writing in Sociology",
      days: "MWF",
      time: "09:15 am-10:20 am",
      cap: "16",
      act: "15",
      rem: "1",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Stephanie   Sears (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
      select: "NR",
      crn: "21604",
      subj: "SOC",
      crse: "297",
      sec: "02",
      cmp: "ODP",
      cred: "4.000",
      title: "Writing in Sociology",
      days: "MWF",
      time: "08:00 am-09:05 am",
      cap: "20",
      act: "12",
      rem: "8",
      wlCap: "0",
      wlAct: "0",
      wlRem: "0",
      xlCap: "0",
      xlAct: "0",
      xlRem: "0",
      instructor: "Jennifer E  Turpin (P)",
      date: "01/25-05/13",
      location: "RMT ",
      attribute: "Core A2 Rhetoric and Comp"
  },
  {
    select: "NR",
    crn: "20405",
    subj: "CS",
    crse: "110",
    sec: "01",
    cmp: "ODP",
    cred: "4.000",
    title: "Introduction to Computer Science I",
    days: "TR",
    time: "09:55 am-11:40 am",
    cap: "30",
    act: "18",
    rem: "12",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Jeffrey Alain  Johnson (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20406",
    subj: "CS",
    crse: "110",
    sec: "02",
    cmp: "ODP",
    cred: "4.000",
    title: "Introduction to Computer Science I",
    days: "TR",
    time: "12:45 pm-02:30 pm",
    cap: "30",
    act: "29",
    rem: "1",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Beste   Yuksel (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20407",
    subj: "CS",
    crse: "110",
    sec: "03",
    cmp: "ODP",
    cred: "4.000",
    title: "Introduction to Computer Science I",
    days: "MW",
    time: "01:00 pm-02:45 pm",
    cap: "30",
    act: "20",
    rem: "10",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Jeffrey Alain  Johnson (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20306",
    subj: "BSDS",
    crse: "100",
    sec: "01",
    cmp: "ODP",
    cred: "4.000",
    title: "Intro to Data Science with R",
    days: "MWF",
    time: "10:30 am-11:35 am",
    cap: "25",
    act: "21",
    rem: "4",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Michael   Ruddy (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20554",
    subj: "ENVS",
    crse: "250",
    sec: "01",
    cmp: "ODP",
    cred: "4.000",
    title: "Environmental Data Analysis",
    days: "MWF",
    time: "10:30 am-11:35 am",
    cap: "30",
    act: "18",
    rem: "12",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Thomas R  MacDonald (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "C",
    crn: "20692",
    subj: "KIN",
    crse: "200",
    sec: "01",
    cmp: "ODP",
    cred: "4.000",
    title: "Measurement and Statistics",
    days: "TR",
    time: "09:55 am-11:40 am",
    cap: "15",
    act: "15",
    rem: "0",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Karen   Francis (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "C",
    crn: "20693",
    subj: "KIN",
    crse: "200",
    sec: "02",
    cmp: "ODP",
    cred: "4.000",
    title: "Measurement and Statistics",
    days: "MWF",
    time: "10:30 am-11:35 am",
    cap: "15",
    act: "17",
    rem: "-2",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Stephanie Lyn Cooper  Hosaka (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "21640",
    subj: "BSM",
    crse: "306",
    sec: "995",
    cmp: "ODP",
    cred: "4.000",
    title: "Business Analytics Fundamentals",
    days: "T",
    time: "06:00 pm-10:00 pm",
    cap: "30",
    act: "21",
    rem: "9",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Brent   Burns (P)",
    date: "03/22-05/04",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20723",
    subj: "MATH",
    crse: "101",
    sec: "01",
    cmp: "ODP",
    cred: "4.000",
    title: "Elementary Statistics",
    days: "MWF",
    time: "09:15 am-10:20 am",
    cap: "25",
    act: "14",
    rem: "11",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Stephen   Yeung (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20724",
    subj: "MATH",
    crse: "101",
    sec: "02",
    cmp: "ODP",
    cred: "4.000",
    title: "Elementary Statistics",
    days: "MWF",
    time: "10:30 am-11:35 am",
    cap: "25",
    act: "16",
    rem: "9",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Stephen   Yeung (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20726",
    subj: "MATH",
    crse: "101",
    sec: "04",
    cmp: "ODP",
    cred: "4.000",
    title: "Elementary Statistics",
    days: "TR",
    time: "09:55 am-11:40 am",
    cap: "25",
    act: "14",
    rem: "11",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Elizabeth S  Mickaily-Huber (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "C",
    crn: "20727",
    subj: "MATH",
    crse: "101",
    sec: "05",
    cmp: "ODP",
    cred: "4.000",
    title: "Elementary Statistics",
    days: "TR",
    time: "12:45 pm-02:30 pm",
    cap: "25",
    act: "26",
    rem: "-1",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Renee Brunelle  Hubert (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20728",
    subj: "MATH",
    crse: "101",
    sec: "06",
    cmp: "ODP",
    cred: "4.000",
    title: "Elementary Statistics",
    days: "TR",
    time: "02:40 pm-04:25 pm",
    cap: "25",
    act: "22",
    rem: "3",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Renee Brunelle  Hubert (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20729",
    subj: "MATH",
    crse: "101",
    sec: "07",
    cmp: "ODP",
    cred: "4.000",
    title: "Elementary Statistics",
    days: "TR",
    time: "04:35 pm-06:20 pm",
    cap: "25",
    act: "21",
    rem: "4",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Olivia Mochong  Mah (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20730",
    subj: "MATH",
    crse: "102",
    sec: "01",
    cmp: "ODP",
    cred: "4.000",
    title: "Biostatistics",
    days: "TR",
    time: "02:40 pm-04:25 pm",
    cap: "25",
    act: "22",
    rem: "3",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Olivia Mochong  Mah (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20732",
    subj: "MATH",
    crse: "106",
    sec: "01",
    cmp: "ODP",
    cred: "4.000",
    title: "Business Statistics",
    days: "MWF",
    time: "10:30 am-11:35 am",
    cap: "30",
    act: "29",
    rem: "1",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Dennis   Schlief (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20734",
    subj: "MATH",
    crse: "106",
    sec: "03",
    cmp: "ODP",
    cred: "4.000",
    title: "Business Statistics",
    days: "TR",
    time: "09:55 am-11:40 am",
    cap: "30",
    act: "25",
    rem: "5",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Van T  Tran (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "C",
    crn: "20737",
    subj: "MATH",
    crse: "106",
    sec: "06",
    cmp: "ODP",
    cred: "4.000",
    title: "Business Statistics",
    days: "TR",
    time: "04:35 pm-06:20 pm",
    cap: "30",
    act: "33",
    rem: "-3",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Kenneth L  Harrington (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20738",
    subj: "MATH",
    crse: "107",
    sec: "01",
    cmp: "ODP",
    cred: "4.000",
    title: "Calculus for the Liberal Arts",
    days: "TR",
    time: "04:35 pm-06:20 pm",
    cap: "30",
    act: "27",
    rem: "3",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Richard John  Lazarowich (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20740",
    subj: "MATH",
    crse: "109",
    sec: "01",
    cmp: "ODP",
    cred: "4.000",
    title: "Calculus and Analytic Geometry I",
    days: "TR",
    time: "12:45 pm-02:30 pm",
    cap: "30",
    act: "22",
    rem: "8",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Emille Davie  Lawrence (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "C",
    crn: "20741",
    subj: "MATH",
    crse: "109",
    sec: "02",
    cmp: "ODP",
    cred: "4.000",
    title: "Calculus and Analytic Geometry I",
    days: "MWF",
    time: "10:30 am-11:35 am",
    cap: "30",
    act: "31",
    rem: "-1",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Tristan R A  Needham (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20742",
    subj: "MATH",
    crse: "109",
    sec: "03",
    cmp: "ODP",
    cred: "4.000",
    title: "Calculus and Analytic Geometry I",
    days: "TR",
    time: "09:55 am-11:40 am",
    cap: "30",
    act: "29",
    rem: "1",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Emille Davie  Lawrence (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20961",
    subj: "PSYC",
    crse: "260",
    sec: "01",
    cmp: "ODP",
    cred: "4.000",
    title: "Psychological Statistics",
    days: "MWF",
    time: "09:15 am-10:20 am",
    cap: "30",
    act: "20",
    rem: "10",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Aline   Hitti (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "C",
    crn: "20962",
    subj: "PSYC",
    crse: "260",
    sec: "02",
    cmp: "ODP",
    cred: "4.000",
    title: "Psychological Statistics",
    days: "TR",
    time: "08:00 am-09:45 am",
    cap: "30",
    act: "30",
    rem: "0",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Alexander   Ochoa (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "C",
    crn: "20963",
    subj: "PSYC",
    crse: "260",
    sec: "03",
    cmp: "ODP",
    cred: "4.000",
    title: "Psychological Statistics",
    days: "TR",
    time: "09:55 am-11:40 am",
    cap: "30",
    act: "30",
    rem: "0",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Alexander   Ochoa (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},
{
    select: "NR",
    crn: "20964",
    subj: "PSYC",
    crse: "260",
    sec: "04",
    cmp: "ODP",
    cred: "4.000",
    title: "Psychological Statistics",
    days: "MWF",
    time: "10:30 am-11:35 am",
    cap: "30",
    act: "18",
    rem: "12",
    wlCap: "0",
    wlAct: "0",
    wlRem: "0",
    xlCap: "0",
    xlAct: "0",
    xlRem: "0",
    instructor: "Aline   Hitti (P)",
    date: "01/25-05/13",
    location: "RMT ",
    attribute: "Core B1 Math or Quant Sci"
},]

// Credit: https://stackoverflow.com/questions/15083548/convert-12-hour-hhmm-am-pm-to-24-hour-hhmm
function convertTime12to24(time12h){
  const [time, modifier] = time12h.split(' ');

  let [hours, minutes] = time.split(':');

  if (hours === '12') {
    hours = '00';
  }

  if (modifier === 'pm') {
    hours = parseInt(hours, 10) + 12;
  }

  return `${hours}:${minutes}`;
}

// Create new date based on the object (course).
// tag start = starting date and time 
// tag end   = eding date and time 
function createNewDate(tag, object){
  
  // Format time to correct format (12 to 24 time)
  function formatTime(time){
    return `${convertTime12to24(time.split('-')[0])}-${convertTime12to24(time.split('-')[1])}`;
  }
  
  // Extract hour based on tag `start` and `end` given formatted time.
  function extractHour(tag, time){
    return tag === 'start' 
           ? parseInt(time.split('-')[0].split(':')[0])
           : parseInt(time.split('-')[1].split(':')[0]);
  }

  // Extract minute based on tag `start` and `end` given formatted time.
  function extractMinute(tag, time){
    return tag === 'start' 
           ? parseInt(time.split('-')[0].split(':')[1])
           : parseInt(time.split('-')[1].split(':')[1]);
  }

  // Extract month based on tag `start` and `end` given formatted time.
  function extractMonth(tag, date){
    return tag === 'start' 
           ? parseInt(date.split('-')[0].split('/')[0])
           : parseInt(date.split('-')[0].split('/')[0]);
  }

  // Extract day based on tag `start` and `end` given formatted time.
  function extractDay(tag, time){
    return tag === 'start' 
           ? parseInt(time.split('-')[0].split('/')[1])
           : parseInt(time.split('-')[0].split('/')[1]);
  }
  
  // Initialize time and date
  let timeX = formatTime(object.time);
  let date = object.date;
  
  return tag === 'start'
         ? new Date(2021, extractMonth('start', date), extractDay('start', date), extractHour('start', timeX), extractMinute('start', timeX))
         : new Date(2021, extractMonth('end', date), extractDay('end', date), extractHour('end', timeX), extractMinute('end', timeX));
}

// Return days of week from object days code using `dict`
// MWF -> Monday Wednesday Friday
function extractDaysOfWeek(object){
  return dict[object.days]
}

// Create new course array using all objects from database
function newCourseArray(objectArray){
  let arr = [];
  for(let i = 0; i< objectArray.length; i++){
    arr.push(new Course(objectArray[i].crn, objectArray[i].title, extractDaysOfWeek(objectArray[i]), createNewDate('start', objectArray[i]), createNewDate('end', objectArray[i])));
  }
  return arr;
}
export function newCourse(object){
  console.log(object.crn);
    return new Course(object.crn, object.title, extractDaysOfWeek(object), createNewDate('start', object), createNewDate('end',object));
}


let courseArray = newCourseArray(result);
// export courseArray to other files
export default courseArray;

